name: CI/CD Workflow for Streamlit Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.8'
  REPO_NAME: 'my-streamlit-app'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Login to Hugging Face
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: huggingface-cli login --token $HUGGINGFACE_TOKEN

      - name: Deploy to Hugging Face Spaces
        run: |
          huggingface-cli repo create ${{ env.REPO_NAME }} --type space || true
          huggingface-cli repo upload . --repo-id ${{ env.REPO_NAME }} --path-in-repo . --commit-message "Deploying Streamlit app"
