# GitHub Actions Workflow: Publish Python Package on Release
# This workflow will automatically upload the Python package to PyPI when a release is published.
# Refer to GitHub's documentation for further details: 
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# Note:
# This workflow uses third-party actions provided by the community. Please review their terms of service,
# privacy policies, and support documentation as they are not governed by GitHub.

name: Upload Python Package

on:
  release:
    types: [published]  # Trigger only when a release is published

permissions:
  contents: read  # Minimal permissions for accessing release contents

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify compatible Python version (adjust as needed)

      # Step 3: Install dependencies for building the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Step 4: Build the Python package
      - name: Build package
        run: python -m build

      # Step 5: Publish the package to PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__  # PyPI username for token-based authentication
          password: ${{ secrets.PYPI_API_TOKEN }}  # Securely access the PyPI API token stored in GitHub Secrets

