name: CI/CD Pipeline for Hugging Face Space Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'  # Specify compatible Python version (adjust as needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build for deployment
        run: python -m build  # Assuming build.py builds the distributable

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Hugging Face Hub
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.env',
              message: 'Update Hugging Face Hub API token',
              content: Buffer.from(`HF_TOKEN=${process.env.HUGGING_FACE_TOKEN}`).toString('base64'),
              branch: 'main'
            })

      - name: Install dependencies (for deployment process)
        run: npm install  # Assuming some npm packages are required for deployment

      - name: Deploy to Hugging Face Spaces
        uses: huggingface/actions/cli/v2
        with:
          repo_id: <your-huggingface-username>/<your-space-name> 
          commit_message: "Deploy from GitHub Actions"
          build_dir: "dist"  # Assuming build.py creates a dist directory
